### ISSUE TITLE
Error on Launch of P4G

### ISSUE THREAD

**Issue by autobotcoop** [Reloaded-Project/Reloaded-II#37] opened 2020-08-12 23:54 UTC
![p4gr2 crash](https://user-images.githubusercontent.com/39393574/90079346-7ef26a80-dcbc-11ea-994c-1ce5db6c006f.jpg)
Hope this means something to you!

**Comment by Sewer56** [comment] 2020-08-13 00:12
This is incredibly sus if I were to say so myself.
I don't have the game in question so I can't really help with regards to reproducing this error. 

This also isn't a loader specific issue, it happens in mod code, so I'm going to close it and link you to https://github.com/zarroboogs/p4gpc.tinyfixes , which appears to have the original source code of the mod.

Note: I did hear P4G almost hits RAM limits on PC due to being a 32bit build but it's very, very weird since it's happening on startup.

**Closed by Sewer56** 2020-08-13 00:12 UTC
