### ISSUE TITLE
Help: [P4G] Reloader II won't run mods

### ISSUE THREAD

**Issue by cosmicobubisi** [Reloaded-Project/Reloaded-II#71] opened 2021-01-08 04:46 UTC
Hello,

I'm having a bit of trouble running mods on Reloader II.

**Attempted troubleshooting:**

All prerequisites have been installed, the Visual C++ ones and the Desktop Runtime/.NET ones, both in x86 and x64.

Reloader II successfully runs P4G, no "failure to load" screen, but it seems that wherever I put my mod files, Reloader II won't load them. I've put them in a folder labeled "mods" next to the .exe file of the game in Steam, next to the P4GModloader, inside of it, I even tried changing the mods directory in the Persona 4 Golden PC Mod Loader, using "configure mod" to specify the folder with the mod data, to no avail.

While I was doing this, Reloader II was stored in the downloads folder. Eventually, I decided to move it to the Persona 4 Golden folder in Steam, thinking that might help, when I got this message:

![image](https://user-images.githubusercontent.com/77137341/103975157-1909f200-5139-11eb-8168-83f97520fade.png)

Any help would be appreciated.

**Additional info:**

The mod I was working with was the [Persona 5 UI Overhaul mod](https://gamebanana.com/gamefiles/12278), however it was just the quickest way to verify if I could run mods.

I would prefer not to use Aemulus Package Manager, as I already tried that. It recognized my files and built them, but the mod still didn't work.

**Comment by Sewer56** [comment] 2021-01-08 05:41
Well aside the super rare config corruption you managed to reproduce; there is no bug here.

Basically, the game uses an archive format `.pac` for storing its assets. What the Persona folks did, or more specifically TGEnigma (TGE) is write their own mod `p4gpc.modloader` for Reloaded which will allow you to load custom files in place of what was archived.

Now, `p4gpc.modloader` searches mods in the `mods` directory inside the game folder; and that is where most Persona mods (which replace files) go. Reloaded mods on the other hand (e.g. `p4gpc.modloader` and 'Tiny Fixes') go in the `Mods` folder which is located in the Reloaded directory by default.

Originally TGE went with an approach of a separate 'mods' folder because they were considering allowing the ability to download mods using a tool called `Mod Compendium`; which had its own mod format; hoping they could be shared with the console game ports. However nobody's really integrated Mod Compendium into `p4gpc.modloader` so you get this weird situation where you get 2 mod folders; one for `p4gpc.modloader` mods and one for `Reloaded` mods.

The way you're meant to do it for `p4gpc.modloader` (which is really bad user experience) is to drop the folder in the `mods` folder in the game directory then in Reloaded press `Configure Mod` for `p4gpc.modloader` and manually add the mod to the `mods` list. Thankfully these days, there is a separate third party launcher for managing `p4gpc.modloader` mods called [Aemulus](https://gamebanana.com/tools/6878) which makes life much easier, you might find it useful. It should really be part of of `modloader`, accessible when you click `Configure Mod` but well; it isn't /shrug.

I'm closing this issue but of course you are free to ask further questions :P.

**Closed by Sewer56** 2021-01-08 05:41 UTC
Labels: untriaged
