### ISSUE TITLE
Sonic Heroes won't load with mods

### ISSUE THREAD

**Issue by YadienThaBegode** [Reloaded-Project/Reloaded-II#134] opened 2022-09-10 18:33 UTC
Every time I try to run Sonic Heroes with Reloaded II, it gives me this error message saying that it was unable to find all dependencies for the mod(s) to be loaded. It also says that a dependency called "reloaded.gamefiles.lodring" is missing. 
![Screenshot (48)](https://user-images.githubusercontent.com/112833102/189496997-673023ea-a8c3-453f-b9e5-663984c5c29c.png)
![Screenshot (47)](https://user-images.githubusercontent.com/112833102/189497021-271fe560-eaae-47d6-8050-a9178042965b.png)

**Comment by Sewer56** [comment] 2022-09-10 18:35
Duplicate of https://github.com/Reloaded-Project/Reloaded-II/issues/117 .
Blame mod author.

**Closed by Sewer56** 2022-09-10 18:35 UTC
Labels: untriaged
