### ISSUE TITLE
Bug: using .net 5.0 x64 on a x64 system causes unknown error on startup

### ISSUE THREAD

**Issue by zxubian** [Reloaded-Project/Reloaded-II#82] opened 2021-04-01 12:51 UTC
**To Reproduce**
1. Try running the app for the first time (without .net 5.0 installed)
2. Get warning about .net 5.0 missing
3. Close all popup windows & quit app
4. [Install .net 5.0 x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer)
5. Try running the app again

**Describe the Bug**
See screenshot below

**Expected Behaviour**
Application starts up

**Screenshots**
![image](https://user-images.githubusercontent.com/8446683/113295992-de78b580-9333-11eb-839a-59f8200e2432.png)

**Comment by Sewer56** [comment] 2021-04-01 13:08
Duplicate of #34

**Closed by Sewer56** 2021-04-01 13:08 UTC
Labels: bug, untriaged
