### ISSUE TITLE
when i add GBF relink and followed the guide i launch it and the game didnt launch

### ISSUE THREAD

**Issue by peesant333** [Reloaded-Project/Reloaded-II#294] opened 2024-02-18 04:47 UTC
**Did you install the Prerequisites?**
You can see them right beside the download button on each official download. 
You'll need all of them as stated.

**As seen on GitHub**:
![image](https://user-images.githubusercontent.com/6697380/90259427-e71e8900-de41-11ea-87aa-0ff27cf5e486.png)

**As seen on GameBanana**:
![image](https://user-images.githubusercontent.com/6697380/90259465-f8679580-de41-11ea-9ef9-08eb3e9c4a2e.png)

**Describe the Issue**
A clear and concise description of what you would like help with.

**Screenshots**

**Additional Resources**
If the issue is related to any external resource e.g. specific version of a mod or pack, consider stating the version or linking the resource in question. Preferably though, mod specific issues should go in their own GitHub repositories as I in most cases would not be able to help.

**Comment by Dogze** [comment] 2024-02-18 14:07
i install all the Prerequisites and when i launch Application, the GBFR mod manager didn't load normally, and the game didn't run at all.
when i remove all the mods and launch application, i got the same log like before but the game could run.
![log](https://github.com/Reloaded-Project/Reloaded-II/assets/94224973/4bacb94f-3e45-4764-9c03-458406348688)

**Comment by Sewer56** [comment] 2024-02-18 14:19
@WistfulHopes probably knows more than I do 😅

**Comment by LucernusV** [comment] 2024-02-20 05:38
I keep getting this error at startup, even though I have the prerequisites installed. I've gone ahead and uninstalled them and even reinstalled them, then restarted PC after, to no avail. 

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/160569307/5a4e9cc0-f42d-44a7-9748-e08d407c8b51)

Followed by this when continuing.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/160569307/2436d4d8-f47a-4310-a060-d1c445a4c055)

**Comment by Shadowborne89** [comment] 2024-02-20 19:44
I am also getting the same error without much luck in troubleshooting.

![Screenshot 2024-02-20 140405](https://github.com/Reloaded-Project/Reloaded-II/assets/160655588/d8c55399-811b-4b42-97bc-e91d91c4e273)

**Comment by Sewer56** [comment] 2024-02-20 19:47
> I am also getting the same error without much luck in troubleshooting.
> 
> ![Screenshot 2024-02-20 140405](https://private-user-images.githubusercontent.com/160655588/306396328-d8c55399-811b-4b42-97bc-e91d91c4e273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTg2NzIsIm5iZiI6MTcwODQ1ODM3MiwicGF0aCI6Ii8xNjA2NTU1ODgvMzA2Mzk2MzI4LWQ4YzU1Mzk5LTgxMWItNGI0Mi05N2JjLWU5MWQ5MWM0ZTI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxOTQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmEyZGRhYmEwZjlhZjM1M2ZhNzZhMGNmN2I3Y2VhNzBmMzIyNmQyMmNiZDdlYzU1YjMxN2U3OTQzYjA2ODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI7bD8C5YDZj89DhxYLI5T0tXMIQi5JrXAlXxTgnUgg)

In your case, you probably got false flagged by defender, as with many other unfortunate victims.

**Comment by Shadowborne89** [comment] 2024-02-20 19:51
> > I am also getting the same error without much luck in troubleshooting.
> > ![Screenshot 2024-02-20 140405](https://private-user-images.githubusercontent.com/160655588/306396328-d8c55399-811b-4b42-97bc-e91d91c4e273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTg2NzIsIm5iZiI6MTcwODQ1ODM3MiwicGF0aCI6Ii8xNjA2NTU1ODgvMzA2Mzk2MzI4LWQ4YzU1Mzk5LTgxMWItNGI0Mi05N2JjLWU5MWQ5MWM0ZTI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxOTQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmEyZGRhYmEwZjlhZjM1M2ZhNzZhMGNmN2I3Y2VhNzBmMzIyNmQyMmNiZDdlYzU1YjMxN2U3OTQzYjA2ODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI7bD8C5YDZj89DhxYLI5T0tXMIQi5JrXAlXxTgnUgg)
> 
> In your case, you probably got false flagged by defender, as with many other unfortunate victims in the past week.
> 
> Not much I can do about it personally. I think I'll briefly cease development on R3 and rewrite all that code in the hope it doesn't get false flagged anymore. We call this 'compulsory bending over to Microsoft Machine Learning in interest of end user security'

Hmm, ok. I see. Things still SEEM to work I suppose? If I hit OK the game loads and whatever I'm running does load to. If that helps.

**Comment by Sewer56** [comment] 2024-02-20 19:54
> > > I am also getting the same error without much luck in troubleshooting.
> > > ![Screenshot 2024-02-20 140405](https://private-user-images.githubusercontent.com/160655588/306396328-d8c55399-811b-4b42-97bc-e91d91c4e273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTg2NzIsIm5iZiI6MTcwODQ1ODM3MiwicGF0aCI6Ii8xNjA2NTU1ODgvMzA2Mzk2MzI4LWQ4YzU1Mzk5LTgxMWItNGI0Mi05N2JjLWU5MWQ5MWM0ZTI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxOTQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmEyZGRhYmEwZjlhZjM1M2ZhNzZhMGNmN2I3Y2VhNzBmMzIyNmQyMmNiZDdlYzU1YjMxN2U3OTQzYjA2ODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI7bD8C5YDZj89DhxYLI5T0tXMIQi5JrXAlXxTgnUgg)
> > 
> > 
> > In your case, you probably got false flagged by defender, as with many other unfortunate victims in the past week.
> > Not much I can do about it personally. I think I'll briefly cease development on R3 and rewrite all that code in the hope it doesn't get false flagged anymore. We call this 'compulsory bending over to Microsoft Machine Learning in interest of end user security'
> 
> Hmm, ok. I see. Things still SEEM to work I suppose? If I hit OK the game loads and whatever I'm running does load to. If that helps.

If you see a console (cmd) window with text, things are probably working fine.

If you don't, extract a [fresh copy](https://github.com/Reloaded-Project/Reloaded-II/releases/latest/download/Release.zip) over your existing Reloaded install, and make sure your AV doesn't nuke `Kernel32AddressDumper.exe`.

**Comment by Shadowborne89** [comment] 2024-02-20 19:57
> > > > I am also getting the same error without much luck in troubleshooting.
> > > > ![Screenshot 2024-02-20 140405](https://private-user-images.githubusercontent.com/160655588/306396328-d8c55399-811b-4b42-97bc-e91d91c4e273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTg2NzIsIm5iZiI6MTcwODQ1ODM3MiwicGF0aCI6Ii8xNjA2NTU1ODgvMzA2Mzk2MzI4LWQ4YzU1Mzk5LTgxMWItNGI0Mi05N2JjLWU5MWQ5MWM0ZTI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxOTQ2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmEyZGRhYmEwZjlhZjM1M2ZhNzZhMGNmN2I3Y2VhNzBmMzIyNmQyMmNiZDdlYzU1YjMxN2U3OTQzYjA2ODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI7bD8C5YDZj89DhxYLI5T0tXMIQi5JrXAlXxTgnUgg)
> > > 
> > > 
> > > In your case, you probably got false flagged by defender, as with many other unfortunate victims in the past week.
> > > Not much I can do about it personally. I think I'll briefly cease development on R3 and rewrite all that code in the hope it doesn't get false flagged anymore. We call this 'compulsory bending over to Microsoft Machine Learning in interest of end user security'
> > 
> > 
> > Hmm, ok. I see. Things still SEEM to work I suppose? If I hit OK the game loads and whatever I'm running does load to. If that helps.
> 
> If you see a console (cmd) window with text, things are probably working fine.
> 
> If you don't, extract a [fresh copy](https://github.com/Reloaded-Project/Reloaded-II/releases/latest/download/Release.zip) over your existing Reloaded install, and make sure your AV doesn't nuke `Kernel32AddressDumper.exe`.

I can confirm the cmd window does appear.

**Comment by Sewer56** [comment] 2024-03-02 02:57
> I keep getting this error at startup, even though I have the prerequisites installed. I've gone ahead and uninstalled them and even reinstalled them, then restarted PC after, to no avail.
> 
> ![image](https://private-user-images.githubusercontent.com/160569307/306145732-5a4e9cc0-f42d-44a7-9748-e08d407c8b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDcyOTYsIm5iZiI6MTcwOTM0Njk5NiwicGF0aCI6Ii8xNjA1NjkzMDcvMzA2MTQ1NzMyLTVhNGU5Y2MwLWY0MmQtNDRhNy05NzQ4LWUwOGQ0MDdjOGI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwMjM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDEzYzFiOGRkYzJmYWM2ZmNhMDNhOTY4OTgwYjAyZGMyMjRkZDg3MjlhMzMwYWJkZjdhZmU3MjBjYzI2NTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ym2hu3tGc85VwYXl3_Zv9Sxcei4UaCmKjid0Ug2UJBU)
> 
> Followed by this when continuing. I've also tried it with and without mods and both times the same thing appears.
> 
> ![image](https://private-user-images.githubusercontent.com/160569307/306146164-2436d4d8-f47a-4310-a060-d1c445a4c055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDcyOTYsIm5iZiI6MTcwOTM0Njk5NiwicGF0aCI6Ii8xNjA1NjkzMDcvMzA2MTQ2MTY0LTI0MzZkNGQ4LWY0N2EtNDMxMC1hMDYwLWQxYzQ0NWE0YzA1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwMjM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTE3ODBhZjQxNmI5MzgyODg4NmI1ODRkM2FhMWM5NDFmM2NkYmZlZWIzZThjOTE4M2VkMjk0OTAyYTBhODZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MdIqgNdtpSmvy8KG_WjqVjSkrKuutucjtg4cKHQSU0A)

In your specific case, see:
- https://github.com/Reloaded-Project/Reloaded-II/issues/308#issuecomment-1974231147

I found the cause, at least.

**Comment by Sewer56** [comment] 2024-03-02 03:00
For @Dogze , I'll put this under:
- https://github.com/Reloaded-Project/Reloaded-II/issues/323

From context, I assume things worked for @Shadowborne89 (comment here or in another issue if not), and the original poster disappeared, so this is probably ok to close.

i.e. Closing as Duplicate

**Closed by Sewer56** 2024-03-02 03:00 UTC
Labels: untriaged
