### ISSUE TITLE
Bug: Uknown error "Failed to DLL inject" when launching game from Reloaded II PC

### ISSUE THREAD

**Issue by mellomarsh123** [Reloaded-Project/Reloaded-II#319] opened 2024-02-24 18:01 UTC
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/161155919/b35050b5-45fb-4012-9570-98fc7f5eaac7)
i dunno why real time protect disable , exclusion too , but nothing work , i don;t use anymod just aplicate launch , game seem run normal but reloaded ii useless

**Comment by Sewer56** [comment] 2024-02-24 19:51
Hi.

Have you tried to extract the contents of a clean [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.8/Release.zip) over your existing install?

**Comment by mellomarsh123** [comment] 2024-02-24 19:53
> Hi.
> 
> Have you tried to extract the contents of a clean [Release.zip](https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.8/Release.zip) over your existing install?
> 
> Chances are your AV might have quarantined the files if you had a detection prior to disabling it, meaning they won't work.

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/161155919/ff92aa29-32f3-4730-a56a-271ae3bbdc74)

**Comment by mellomarsh123** [comment] 2024-02-24 19:58
this work normal at first but when i restore windown , and install again this happen

**Comment by Sewer56** [comment] 2024-02-24 20:20
Worst case scenario, go to `Edit Application` and hit `Deploy ASI Loader`. then boot game by booting it regularly.

**Comment by Sewer56** [comment] 2024-02-25 23:14
I'm closing this and related issues as 'caused by Windows Defender' or 'caused by DLL Injection code which no longer exists starting with 1.25.9'. Open a new issue if you have problems after updating.

**Closed by Sewer56** 2024-02-25 23:14 UTC
Labels: bug, untriaged
