### ISSUE TITLE
[Stale] [User got Defender'd, but now has unrelated boot issue with Granblue]

### ISSUE THREAD

**Issue by TheZathel** [Reloaded-Project/Reloaded-II#312] opened 2024-02-21 22:12 UTC
When attempting to launch "PS5 Button Icons - Reloaded" mod (from Nexus mods) for Granblue Fantasy: Relink  from reloaded level (mod description says its a mandatory step to get it working first time) Reloaded displays following error:
![image](https://github.com/Reloaded-Project/Reloaded-II/assets/160792937/589723ec-858d-4e6e-a09e-15311cbaf314)
Game launches fine, but mod clearly does not work (button prompts are not replaced).
[gbfrelink.ui.ps5buttonsb.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14365728/gbfrelink.ui.ps5buttonsb.zip)

I'm fairly sure i didn't cock up mod enabling or reloaded installation - only issue was getting past Windows Defender on initial setup.exe download.

**Comment by Sewer56** [comment] 2024-02-21 22:14
Chances are defender blacklisted `Kernel32AddressDumper.exe` during the install. 
If you extract the latest Release.zip: https://github.com/Reloaded-Project/Reloaded-II/releases/download/1.25.8/Release.zip after adding an exclusion for the Reloaded folder, things will probably work fine. Let me know if they do.

**Comment by TheZathel** [comment] 2024-02-21 22:45
Added Reloaded II folder to Exclusions, unzipped fresh release zip into the folder, launched, Reloaded started quickly flickering some sort of additional window but it refuses to stay on screen long enough for me to try and capture what it says. Game does not actually launch. App still launches fine if mod is removed, when it is readded, but trying to run the game with it triggers the issue.

**Comment by Sewer56** [comment] 2024-02-21 22:49
Nab a log file

![image](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/432ed1e4-3f5e-4f9f-a701-5701a2ec3cb2)

Chances are it's a duplicate of:
- https://github.com/Reloaded-Project/Reloaded-II/issues/292
- https://github.com/Reloaded-Project/Reloaded-II/issues/308

**Comment by TheZathel** [comment] 2024-02-21 23:01
[OldLogs.zip](https://github.com/Reloaded-Project/Reloaded-II/files/14366042/OldLogs.zip)

**Comment by TheZathel** [comment] 2024-02-21 23:32
It either works or I resign myself to search for another avenue. Thanks for trying to troubleshoot this.

**Comment by Sewer56** [comment] 2024-03-02 02:26
Were you successful? Am curious.

**Comment by Maxturbation** [comment] 2024-03-06 04:03
I'm having the exact same issue to the tea. My oldlogs folder is empty as well. I didnt have any trouble with defender though. The ASI loader did not work either, saying "Unable to load Reloaded.Mod.Loader.Bootstrapper.asi, Error: 126"

**Comment by Sewer56** [comment] 2024-03-06 04:07
> Error: 126"

It's different in your case.

Error 126 means it can't load a DLL this DLL depends on.
In other words, one of the following:
![20240306_04h07m05s](https://github.com/Reloaded-Project/Reloaded-II/assets/6697380/3f0192d6-81b0-499d-8b71-9e23d1367f95)

Chances are, your install of Visual C++ Redistributable is corrupt or missing.

**Comment by Maxturbation** [comment] 2024-03-06 07:45
You friend @Sewer56 , are a saint. Tysm, im sure its all simple to you, but i have no clue how you even begin to just know stuff like that off the top of your head, and even included a screenshot too. Much love, it worked perfect!

**Closed** 2024-04-07 16:28 UTC
Labels: bug, untriaged
