### ISSUE TITLE
[Linux] Bug: Reload does not run through Wine 8.0

### ISSUE THREAD

**Issue by ioletsgo** [Reloaded-Project/Reloaded-II#188] opened 2023-02-03 08:05 UTC
I've tried almost everything in the book and i'm simply unable to run Reload-II on Wine 8.0
Whenever I try to run it through the Terminal, I simply get this output
```[ioletsgo@IdeaPad Reloaded-II]$ wine Reloaded-II32.exe
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
ioctl (GFEATURE): Broken pipe
ioctl (GFEATURE): Broken pipe
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0098:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0098:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0098:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0024:fixme:heap:GetNumaHighestNodeNumber semi-stub: 005BF65C
0024:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\Program Files (x86)\\dotnet\\shared\\Microsoft.NETCore.App\\7.0.2\\mscordaccore.dll", 01200000) stub
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 07F83241, 28) stub
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 05735E64, 34) stub
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 05731D18, 38) stub
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0572B660, 17) stub
0024:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0024:fixme:ntdll:RtlGetCurrentProcessorNumberEx (005BE8C8) :semi-stub
```
the Semi-stub gets line repeated about a hundred times before ending on a 
```011c:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000019BFC0 0000000000000000 000000000019BFB8) returning a dummy value (current locale)
011c:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 000000000019BFC0 000000000019BF10 000000000019BFB8) returning a dummy value (current locale)
011c:fixme:virtual:NtFlushProcessWriteBuffers stub
011c:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x379f92d
[ioletsgo@IdeaPad Reloaded-II]$ 
```

**Comment by Sewer56** [comment] 2023-02-03 12:33
Potentially a regression in Wine 8.X, not sure yet; nothing seems to stand out in the log; and I'm not really sure how I would get the stack trace of a .NET application; [try to make a minidump, maybe we can pull it from there](https://linux.die.net/man/1/winedbg).

In the meantime, since I saw a locale related fixme, maybe you can try adding 
```
     "System.Globalization.UseNls": true,
```

Under the `configProperties` node in the `.runtimeconfig.json` file, see how that goes.

**Comment by Sewer56** [comment] 2023-02-03 13:13
Please note: You should report this to the Wine devs *especially* if it only repros for you in 8.0; since that would be a regression.

While I do work around 2/3 minor things not implemented in Wine in Reloaded, *technically this is a bad idea and Wine developers really don't want us to do that*! 

I did it because at the time the issues I ran into (already reported) didn't look like they were to be fixed any time soon.

**Comment by anzix** [comment] 2023-05-04 09:54
idk, works fine with Proton 8.0-2 launching through protontricks with argument `--nogui`
```sh
protontricks-launch --appid 2990 Setup.exe --nogui
```

**Comment by Sewer56** [comment] 2024-02-19 21:19
This was fixed in upstream Wine a while back, so not much to do here. Wine was failing to run .NET 7 programs in general at the time, not just Reloaded. Thankfully we're past t hat.

**Closed by Sewer56** 2024-02-19 21:19 UTC
Labels: bug, untriaged
