### ISSUE TITLE
[Game won't open and stuck]

### ISSUE THREAD

**Issue by ohniubibioh** [Reloaded-Project/Reloaded-II#402] opened 2024-06-28 16:27 UTC
MMMMMMMMMMMMMMMMMMdo`        hMMM+ +MMMh
                                        MMMMMMMMMMMMMMMMMMMMh       `MMMM` dMMM/
                                        MMMM-          `yMMMN       +MMMh .MMMN`
                                        MMMM-          `sMMMN       dMMM/ sMMMy
                                        MMMM- .sMMMMMMMMMMMMd      -MMMN  NMMM:
                                        MMMM-   `sNMMMMMMMdo`      sMMMy :MMMm
                                        MMMM-     `oNMMMMy-        NMMM- yMMMo
                                        MMMM-       `oNMMMMh-     :MMMm `MMMM.
                                        MMMM-         `+mMMMMh:   yMMMo /MMMd
                                        MMMM-            /mMMMMd:`MMMM. dMMM+

                                                 1.27.11 // .NET 8.0.6

[Reloaded] Create Loader | Time: 41ms
[Reloaded] Loading 1 Mod(s).
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - Location: C:\Users\yangguang\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[Reloaded] - LoadTime: 11ms
[Reloaded] Loaded via: C:\Users\yangguang\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
Warning: Steam Stub (Embedded Steam DRM) found.
This means EXE is encrypted at launch. Support for bypassing this DRM is experimental.
If you find issues, remove the DRM using `Steamless` or try using ASI Loader `Edit Application -> Deploy ASI Loader`
[Reloaded] DRM Requiring Delayed Initialization (SteamStub) Found.
Reloaded will try to initialize late to bypass this DRM.
Please note this feature is experimental.
If you encounter issues, report and/or try ASI Loader `Edit Application -> Deploy ASI Loader`
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[R-II SteamHook] Found Steam Library Entry with Id 881020. Dropping steam_appid.txt.
[Reloaded] Setting Up Hooks (Async) | Time: 131ms
[Reloaded] Loading Mods (Total) | Time: 160ms
[Reloaded] Total Loader Initialization Time: 229ms
[Reloaded] Delay Injection via Entry Point: winmm, timeGetDevCaps
[Reloaded] Loading via Delayed Injection (DRM Workaround)
[Reloaded] Current Process Location: D:\SteamLibrary\steamapps\common\Granblue Fantasy Relink\granblue_fantasy_relink.exe
[Reloaded] Loading 2 Mod(s).
[Reloaded]
[Reloaded] Loading: Granblue Fantasy Relink Mod Manager
[Reloaded] - AppId   : gbfrelink.utility.manager
[GBFRelinkManager] StartEx
[Reloaded] - Location: C:\Users\yangguang\Desktop\Reloaded-II\Mods\gbfrelink.utility.manager1.1.0\ModConfig.json

**Comment by Sewer56** [comment] 2024-06-28 16:57
This is a duplicate of #323 
Cause is currently unknown, but you might be able to get away with `Deploy ASI Loader` option in 'Esit Application', as per feedback there.

**Closed by Sewer56** 2024-06-28 16:57 UTC
Labels: untriaged
