### ISSUE TITLE
Reloaded II not loading any P5R mods other than essentials

### ISSUE THREAD

**Issue by SheerluckHolmes** [Reloaded-Project/Reloaded-II#155] opened 2022-11-02 18:07 UTC
I've updated and re-installed Reloaded II and have the latest .NET updates, but none of my P5R mods besides the mod loader pack seem to load. Like, it just skips over them.

[```
Reloaded] Create Loader | Time: 62ms

[Reloaded] Current Process Location: D:\SteamLibrary\steamapps\common\P5R\P5R.exe

[Reloaded] Loading Assembly Metadata for Inter Mod Communication, Determining Unload Support etc.: Complete 13ms

[Reloaded] Prepared Mod: reloaded.sharedlib.hooks: Complete 2ms

[Reloaded] Prepared Mod: p5rpc.ui.nocinemascope: Complete 0ms

[Reloaded] Prepared Mod: No More More AOA Fadein: Complete 0ms

[Reloaded] Prepared Mod: p5rpc.ambushbgmexpansion: Complete 0ms

[Reloaded] Prepared Mod: p5rpc.betterletters: Complete 0ms

[Reloaded] Prepared Mod: p5rpc.skins.menumodelscramble: Complete 0ms

[Reloaded] Prepared Mod: p5rpc.modloader: Complete 4ms

[Reloaded] Prepared Mod: Reloaded.Memory.SigScan.ReloadedII: Complete 6ms

[Reloaded] Prepare All Mods (Total): Complete 10ms

[Reloaded] Initialized Mod: reloaded.sharedlib.hooks: Complete 0ms

[Reloaded] Initialized Mod: Reloaded.Memory.SigScan.ReloadedII: Complete 1ms

[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.

[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.

[R-II SteamHook] Found Steam Library Entry with Id 1687950. Dropping steam_appid.txt.

[Reloaded] Setting Up Hooks (Async) | Time: 146ms

[Reloaded] Initialized Mod: p5rpc.modloader: Complete 120ms

[Reloaded] Initialized Mod: p5rpc.ui.nocinemascope: Complete 3ms

[Reloaded] Initialized Mod: No More More AOA Fadein: Complete 0ms

[Reloaded] Initialized Mod: p5rpc.ambushbgmexpansion: Complete 0ms

[Reloaded] Initialized Mod: p5rpc.betterletters: Complete 0ms

[Reloaded] Initialized Mod: p5rpc.skins.menumodelscramble: Complete 0ms

[Reloaded] Initialized All Mods (Total): Complete 127ms

[Reloaded] Loading Mods (Total) | Time: 314ms

[Reloaded] Total Loader Initialization Time: 377ms

[Reloaded II Bootstrapper] Ultimate ASI Loader Entrypoint Hit
```

**Comment by Sewer56** [comment] 2022-11-02 18:08
Maybe you disabled `Mod Support` in P5R Essentials' config.

**Comment by SheerluckHolmes** [comment] 2022-11-02 18:17
It's enabled - but still no mods loading.

![image](https://user-images.githubusercontent.com/117306143/199569492-5b17124c-a371-4870-8f84-2610de111dc0.png)

**Comment by Sewer56** [comment] 2022-11-02 18:21
Can you set LogLevel to Debug and post the full log file?

(You can find log file in the drop-down in Settings/Main R2 screen)

**Comment by SheerluckHolmes** [comment] 2022-11-02 18:24
Where is that option?

**Comment by SheerluckHolmes** [comment] 2022-11-02 18:24
[2022-11-02 18.23.54 ~ P5R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/9923156/2022-11-02.18.23.54.P5R.txt)

**Comment by Sewer56** [comment] 2022-11-02 18:24
In the screenshot you posted actually.

**Comment by SheerluckHolmes** [comment] 2022-11-02 18:26
[2022-11-02 18.25.34 ~ P5R.txt](https://github.com/Reloaded-Project/Reloaded-II/files/9923167/2022-11-02.18.25.34.P5R.txt)

Here's the debug version

**Comment by Sewer56** [comment] 2022-11-02 18:28
Can't really comment, according to log everything is working fine.

**Comment by SheerluckHolmes** [comment] 2022-11-02 18:29
I find it strange that the mods are taking 0ms to load and not appearing

**Comment by Sewer56** [comment] 2022-11-02 18:36
Actually, I stand corrected, I know what the issue is.

See log `D:\Documents\P4G Mods\Tools\Reloaded-II\Mods\p5rpc.sound.p3p3fmd\P5REssentials/CPK`

Binding Directory `C:\Users\alexs\Desktop\Reloaded-II\User\Mods\p5rpc.modloader\Bind\17928\R2 `

====

There's currently a limitation in P5R Essentials where the User folder for Reloaded and the Mods need to be on the same drive because hardlinks are used.

This will be fixed in the future, but for now you must move the user folder to the same drive as where your mods are located. 

Close Reloaded, Open the Config File from launcher and change the path of your `ModUserConfigDirectory` to use the same drive (D) as the folder storing your mods, then move the old folder to wherever you set your new path.

**Comment by SheerluckHolmes** [comment] 2022-11-02 19:13
That's perfect. Thank you.

**Closed** 2022-11-02 20:45 UTC
Labels: untriaged

**Comment by Sewer56** [comment] 2022-11-03 17:35
![image](https://user-images.githubusercontent.com/6697380/199793699-3fa1d52d-89d2-44d8-83a1-4c7942e53c5a.png)
![image](https://user-images.githubusercontent.com/6697380/199793779-51bc2e08-0d15-4dd2-a2ea-56b30c440314.png)

If the `Open Config File` doesn't open a file, you'll be able to find the (`.json`) config if you click `View Log Files` and go one folder up to find `ReloadedII.json`

**Comment by SheerluckHolmes** [comment] 2022-11-03 17:45
That's all on the D:// Drive. Moved the Reloaded Launcher over too, but now antivirus is flagging latest update.

**Comment by Sewer56** [comment] 2022-11-03 17:45
I hate when that happens; please just report as false positive.

**Comment by SheerluckHolmes** [comment] 2022-11-03 17:47
All good. Thank you!

**Comment by Sewer56** [comment] 2022-11-03 18:13
[Download an earlier release from Releases](https://github.com/Reloaded-Project/Reloaded-II/releases), extract `Release.zip` ontop of your existing Reloaded-II folder.

**Comment by SheerluckHolmes** [comment] 2022-11-03 18:17
Case Closed. I'll wait on 1.2.4 to update again. Thank you!
