### ISSUE TITLE
Bug: Update prompt fails when updating to v1.22.8+; Falsely claims .NET is not installed.

### ISSUE THREAD

**Issue by iSharingan** [Reloaded-Project/Reloaded-II#166] opened 2022-11-20 07:40 UTC
**Describe the Bug**
Updating from v.1.22.7 to 1.22.8/1.22.9 after launching Reloaded II 

**To Reproduce**
1. Launch Reloaded II v1.22.7
2. Click on a configured game (in my case Persona 5 Royal)
3. Update Prompt appears. Click on Update.
4. Update download progress bar completes, then attached error window appears (.NET 7.0.0 is already installed - and was re-installed to be sure, though the problem persists)

**Expected Behavior**
Update should install properly and not fail when prompting for an already-installed version of .NET

**Screenshots**
![Error](https://user-images.githubusercontent.com/3332462/202891112-b4b85270-9690-48d6-a4fd-19d239e2127c.PNG)

**Additional Context**
Reloaded-II runs fine as I previously installed and updated it via the prompt fine up until 1.22.7. Issues only began with v1.22.8.

**Comment by Sewer56** [comment] 2022-11-20 15:47
Working as intended.

Builds prior to 1.22.8 were built with preview SDK and accepted pre-release versions of .NET 7, current builds now expect release version since .NET 7 just released 

Normally a launcher upgrade would upgrade runtime alongside it if needed but due to a bug involving prerelases specifically, that wasn't the case and is only fixed on 1.22.9.

**Closed by Sewer56** 2022-11-20 15:47 UTC
Labels: bug, untriaged

**Comment by iSharingan** [comment] 2022-11-20 17:58
Reloaded-II now updates after sending to the correct .NET 7.0.0 link, but still throws an error like its not installed (see screenshot).

![Error](https://user-images.githubusercontent.com/3332462/202917906-be7251d0-1b55-4040-9a94-e753407002ad.PNG)

Closing the new error still lets you use Reloaded-II but the popup shouldn't be appearing

**Comment by Sewer56** [comment] 2022-11-20 18:01
This is working as intended.

Launcher only uses x64 Runtime (which you got prompt for and installed) but 32-bit games require the x86 version and my own runtime checker catches it (as in screenshot).

Usually installing all runtimes would be automated on launcher update but due to that aforementioned bug, it wasn't. Sorry for the inconvenience.

**Comment by Sewer56** [comment] 2023-01-19 16:21
As per the initial comment; the bug that originally caused OP's issue was fixed in `1.22.9`.

There was a bug/oversight in the library for checking runtime installations that assumed binaries built against the final .NET 7 SDK could be ran by the preview runtime; which was not the case.

Reloaded scans next version's download for any missing runtimes and downloads+installs them before updating self. In OP's specific case, this did not happen due to the wrong assumption listed above; this was fixed the day before this issue was filed.
