### ISSUE TITLE
Help: Please help me with <X>

### ISSUE THREAD

**Issue by Kohagi1** [Reloaded-Project/Reloaded-II#488] opened 2024-11-18 18:14 UTC
I tried to download reloaded 2 and on their website it tells me to open setup-linux using the protontricks launcher to select the game to download but when I open setup-linux with the protontricks launcher, I select P4G and this appears error, what do I do to resolve it?
![image](https://github.com/user-attachments/assets/0e5bdb6a-3fb6-4880-8d59-9c69c832d4cf)

**Comment by Sewer56** [comment] 2024-11-20 19:58
I thought I responded, apologies, I must have missed it.

The answer is [here](https://reloaded-project.github.io/Reloaded-II/LinuxSetupGuideNewExtra/#installing-protontricks-via-flatpak) in the 'Installing Protontricks via Flatpak' section. You need to give `protontricks` filesystem access, otherwise the Reloaded installer is unable to add a shortcut to your native Linux desktop.

![Image](https://github.com/user-attachments/assets/bd92ec67-b89f-4c9f-b0f0-8480691c00ad)


Duplicate of:
- https://github.com/Reloaded-Project/Reloaded-II/issues/479

**Closed by Sewer56** 2024-11-20 19:58 UTC
Labels: untriaged
