### ISSUE TITLE
Fatal error launching Persona 4

### ISSUE THREAD

**Issue by Dundakuso** [Reloaded-Project/Reloaded-II#411] opened 2024-07-31 23:21 UTC
Got a problem lauchig Persona 4 only, Persona 5 still launching perfectly.
Idk what to do, I already uninstalled Persona 4 and deleted the files, and downloaded them again from Steam, but the problem persists. Here is the code that it gives me every time I try to launch it:

                                    MMMMMMMMMMMMMMMMMMdo`        hMMM+ +MMMh
                                    MMMMMMMMMMMMMMMMMMMMh       `MMMM` dMMM/
                                    MMMM-          `yMMMN       +MMMh .MMMN`
                                    MMMM-          `sMMMN       dMMM/ sMMMy
                                    MMMM- .sMMMMMMMMMMMMd      -MMMN  NMMM:
                                    MMMM-   `sNMMMMMMMdo`      sMMMy :MMMm
                                    MMMM-     `oNMMMMy-        NMMM- yMMMo
                                    MMMM-       `oNMMMMh-     :MMMm `MMMM.
                                    MMMM-         `+mMMMMh:   yMMMo /MMMd
                                    MMMM-            /mMMMMd:`MMMM. dMMM+

                                                 1.27.11 // .NET 8.0.7

[Reloaded] Create Loader | Time: 26ms
[Reloaded] Loading 1 Mod(s).
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[Reloaded] - LoadTime: 6ms
[Reloaded] Loaded via: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\Persona 4 Golden\P4G.exe
[Reloaded] Loading 15 Mod(s).
[Reloaded]
[Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[Reloaded] - LoadTime: 4ms
[Reloaded]
[Reloaded] Loading: File Emulation Framework: Base Mod
[Reloaded] - AppId   : reloaded.universal.fileemulationframework
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework\ModConfig.json
Starting FileEmulationFramework
[Reloaded] - LoadTime: 120ms
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[Reloaded]
[Reloaded] Loading: AWB Emulator for File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.awb
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.awb\ModConfig.json
Starting AWB.Stream.Emulator
[R-II SteamHook] Found Steam Library Entry with Id 1113000. Dropping steam_appid.txt.
[Reloaded] Setting Up Hooks (Async) | Time: 151ms
[Reloaded] - LoadTime: 14ms
[Reloaded]
[Reloaded] Loading: CRI FileSystem V2 Hook
[Reloaded] - AppId   : crifs.v2.hook
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\crifs.v2.hook\ModConfig.json
[Reloaded] - LoadTime: 34ms
[Reloaded]
[Reloaded] Loading: AWB Emulator Support for CRI FileSystem V2 Hook
[Reloaded] - AppId   : CriFs.V2.Hook.Awb
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\CriFs.V2.Hook.Awb\ModConfig.json
[Reloaded] - LoadTime: 6ms
[Reloaded]
[Reloaded] Loading: PAK Emulator for File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.pak
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.pak\ModConfig.json
Starting PAK.Stream.Emulator
[Reloaded] - LoadTime: 8ms
[Reloaded]
[Reloaded] Loading: BMD Emulator For File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.bmd
[Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bmd\ModConfig.json
Starting BMD.File.Emulator
[Reloaded] - LoadTime: 261ms
[Reloaded]
[Reloaded] Loading: BF Emulator for File Emulation Framework
[Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.bf
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.bf\ModConfig.json
Starting BF.File.Emulator
[Reloaded] - LoadTime: 236ms
[Reloaded]
[Reloaded] Loading: SPD Emulator for File Emulation Framework
[Reloaded] - AppId   : reloaded.universal.fileemulationframework.spd
[Reloaded] [LoaderAPI] Warning: GetController<IReloadedHooks> returned null.
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.universal.fileemulationframework.spd\ModConfig.json
Starting SPD.File.Emulator
[Reloaded] - LoadTime: 10ms
[Reloaded]
[Reloaded] Loading: Persona Essentials
[Reloaded] - AppId   : p5rpc.modloader
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\p5rpc.modloader\ModConfig.json
[Reloaded] - LoadTime: 9ms
[Reloaded]
[Reloaded] Loading: Yosuke Romance Full
[Reloaded] - AppId   : p4gpc.mudkipports.yosukeromanceFULL
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\p4gpc.mudkipports.yosukeromanceFULL\ModConfig.json
[Reloaded] - LoadTime: 0ms
[Reloaded]
[Reloaded] Loading: Social Link Cheat Sheet 64
[Reloaded] - AppId   : p4gpc.sociallinkcheatsheet64
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\p4gpc.sociallinkcheatsheet64\ModConfig.json
[Reloaded] - LoadTime: 0ms
[Reloaded]
[Reloaded] Loading: Cheat Sheet Compatibility Yosuke
[Reloaded] - AppId   : p4gpc.cheatsheetcompatibilityyosuke
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\p4gpc.cheatsheetcompatibilityyosuke\ModConfig.json
[Reloaded] - LoadTime: 0ms
[Reloaded]
[Reloaded] Loading: Classroom Cheat Sheet 64
[Reloaded] - AppId   : p4gpc.classroomcheatsheet64
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\p4gpc.classroomcheatsheet64\ModConfig.json
[Reloaded] - LoadTime: 0ms
[Reloaded]
[Reloaded] Loading: Cooking Cheat Sheet 64
[Reloaded] - AppId   : p4gpc.cookingcheatsheet64
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\p4gpc.cookingcheatsheet64\ModConfig.json
[Reloaded] - LoadTime: 0ms
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Fatal error while logging another fatal error.
Fatal error while logging another fatal error.

**Comment by Sewer56** [comment] 2024-07-31 23:29
@Dundakuso I suggest turning off all mods and re-enabling them one by one. Maybe it's a specific combination.

The `Save Mod Set` and `Load Mod Set` features might help to quickly save/restore the mods that are enabled and not enabled.

**Comment by Dundakuso** [comment] 2024-07-31 23:56
None of the mods works individually, but the only one that gives me a different code is CRI FileSystem V2 Hook, that thinking about it, it was the mod that was updated today, yesterday I was able to launch Persona 4 without problems... Sorry for the inconveniences and thanks in advance!

                                        MMMMMMMMMMMMMMMMMMdo`        hMMM+ +MMMh
                                        MMMMMMMMMMMMMMMMMMMMh       `MMMM` dMMM/
                                        MMMM-          `yMMMN       +MMMh .MMMN`
                                        MMMM-          `sMMMN       dMMM/ sMMMy
                                        MMMM- .sMMMMMMMMMMMMd      -MMMN  NMMM:
                                        MMMM-   `sNMMMMMMMdo`      sMMMy :MMMm
                                        MMMM-     `oNMMMMy-        NMMM- yMMMo
                                        MMMM-       `oNMMMMh-     :MMMm `MMMM.
                                        MMMM-         `+mMMMMh:   yMMMo /MMMd
                                        MMMM-            /mMMMMd:`MMMM. dMMM+

                                                 1.27.11 // .NET 8.0.7


[Reloaded] Create Loader | Time: 29ms
[Reloaded] Loading 1 Mod(s).
[Reloaded]
[Reloaded] Loading: Reloaded II Shared Lib: Reloaded.Hooks
[Reloaded] - AppId   : reloaded.sharedlib.hooks
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\reloaded.sharedlib.hooks\ModConfig.json
[Reloaded] - LoadTime: 5ms
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Loader\x64\Bootstrapper\Reloaded.Mod.Loader.Bootstrapper.dll
[Reloaded] Current Process Location: C:\Program Files (x86)\Steam\steamapps\common\Persona 4 Golden\P4G.exe
[Reloaded] Loading 2 Mod(s).
[Reloaded]
[Reloaded] Loading: Library: Reloaded.Memory.Sigscan for Reloaded II
[Reloaded] - AppId   : Reloaded.Memory.SigScan.ReloadedII
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\Reloaded.Memory.SigScan.ReloadedII\ModConfig.json
[Reloaded] - LoadTime: 5ms
[Reloaded]
[Reloaded] Loading: CRI FileSystem V2 Hook
[Reloaded] - AppId   : crifs.v2.hook
[Reloaded] - Location: C:\Users\Dunda\OneDrive\Desktop\Reloaded-II\Mods\crifs.v2.hook\ModConfig.json
[Reloaded] - LoadTime: 43ms
[R-II SteamHook] SteamAPI_RestartAppIfNecessary hooked successfully.
[R-II SteamHook] SteamAPI_IsSteamRunning hooked successfully.
[R-II SteamHook] Found Steam Library Entry with Id 1113000. Dropping steam_appid.txt.
[Reloaded] Setting Up Hooks (Async) | Time: 204ms
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Reloaded.Memory.Sigscan.Scanner.FindPatternAvx2(Byte*, Int32, System.String)
   at Reloaded.Memory.Sigscan.Scanner+<>c__DisplayClass15_0.<FindPatternsCached>b__1(System.Tuple`2<Int32,Int32>)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass43_0`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<PartitionerForEachWorker>b__1(System.Collections.IEnumerator ByRef, Int64, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

**Comment by Sewer56** [comment] 2024-08-01 00:18
It's sleeping hours for me, but you can downgrade in the meantime:

```
r2:https://github.com/Sewer56/CriFs.V2.Hook.ReloadedII/releases/download/2.3.1/CriFs.V2.Hook2.3.1.7z
```

Try pasting that into your browser.

**Comment by Dundakuso** [comment] 2024-08-01 00:21
Rest well, thanks I will try it!

**Comment by Sewer56** [comment] 2024-08-01 00:22
(Do let me know if it os the culprit. The new functionality there isn't super urgent, so I can still pull the update if needed)

Maybe there's a subtle bug with sigscanner somewhere.

**Comment by Dundakuso** [comment] 2024-08-01 00:24
It works with the downgrade, THANK YOU SO MUCH!

**Comment by Sewer56** [comment] 2024-08-01 00:24
I'll look into the root cause tomorrow, potentially a bug out there in the scanner.

**Comment by Sewer56** [comment] 2024-09-19 02:27
The bug causing this was fixed day after my response. I forgot to close the issue.

**Closed by Sewer56** 2024-09-19 02:27 UTC
Labels: accepted
